/*

This is a program for an autonomous robot called "Lil-Boty" which allows it to:
 1. Detect obstacles to avoid collisions
 2. Carry a small payload from one point to the desired target(which it locates itslef)
 3. Signal Task completion

 Authors: Nicholas Castellani, Rissalat Kapdi, David Cheung
*/


#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in2,    IR2,            sensorReflection)
#pragma config(Sensor, in8,    IR1,            sensorReflection)
#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl4,  EMAGNET,        sensorNone)
#pragma config(Sensor, dgtl12, ,               sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           motorright,    tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port3,           motorlift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motorIR,       tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           EMAGNET,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          motorleft,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int IRmax=0;
int pos=0;
int x=0;
int n=0;
int V=0;
int v=0;
int s=0;
task trace1(){
	while(true){
		if(SensorValue(IR1)<IRmax-2){
			motor[motorIR]=-30;
		}//closes <IRmax if loop

	}
}
task trace2(){
	while(true){
		if(SensorValue(IR1)<IRmax-2){
			motor[motorIR]=30;
		}//closes <IRmax if loop

	}
}



void run(){


	while(true){

		motor[EMAGNET]=127;
		if (SensorValue(button1)==true){
			resetMotorEncoder(motorIR);
			SensorValue(button1)=true;
			while (true){
				if (getMotorEncoder(motorIR)<50){
					motor[motorIR]=0;
					resetMotorEncoder(motorIR);
					while(getMotorEncoder(motorIR)<310){
						motor[motorIR]=50;
						if(SensorValue(IR1)>IRmax){
							IRmax=SensorValue(IR1);
							pos=getMotorEncoder(motorIR);
						}//closes IR1 if loop

					}//closes motorIR 90 loop
					motor[motorIR]=0;

					while(getMotorEncoder(motorIR)>-310){
						motor[motorIR]=-50;

						if(SensorValue(IR1)>IRmax){
							IRmax=SensorValue(IR1);
							pos=getMotorEncoder(motorIR);
						}//closes IR1 if loop

					}//closes motorIR -180 loop

					motor[motorIR]=0;
				}//back to zero point

				motor[motorIR]=0;

				while(getMotorEncoder(motorIR) < pos){
					motor[motorIR]=24;

				}//closes motorIR reposition loop

				motor[motorIR]=0;

				if(getMotorEncoder(motorIR) > 0){
					startTask(trace1);
					while(getMotorEncoder(motorIR) > 0){
						motor[motorIR]=0;
						motor[motorleft]=-35;
						motor[motorright]=-35;
					}//closes while loop
					stopTask(trace1);
					motor[motorleft]=0;
					motor[motorright]=0;
					motor[motorIR]=0;
					x=1;
				}// closes <0 if loop

				if(getMotorEncoder(motorIR) < 0 && x==0){
					startTask(trace2);
					while(getMotorEncoder(motorIR)<0){
						motor[motorIR]=0;
						motor[motorleft]=35;
						motor[motorright]=35;
					}//closes while loop
					stopTask(trace2);
					motor[motorleft]=0;
					motor[motorright]=0;
					motor[motorIR]=0;

				}// closes >0 if loop


				motor[motorIR]=0;

				resetMotorEncoder(motorIR);



				//start of the drive forward loop
				while(true){


					while(getMotorEncoder(motorIR)<(300-v)){
						motor[motorIR]=60-V;
						if ((SensorValue(sonar)<3.25 && SensorValue(sonar)>0) && (SensorValue(IR1)> 500)){
							motor[motorleft]=0;
							motor[motorright]=0;
							motor[motorIR]=0;
							wait1Msec(250);
							motor[motorlift]=-50;
							wait1Msec(750);
							motor[motorlift]=0;
							wait1Msec(100);
							motor[EMAGNET]=0;
							wait1Msec(1000);
							motor[motorlift]=40;
							wait1Msec(750);
							motor[motorlift]=0;
							motor[motorleft]=-50;
							motor[motorright]=50;
							wait1Msec(1500);
							motor[motorleft]=0;
							motor[motorright]=0;
							wait1Msec(1000);
							/*
							for(int y=0; y<3; y++){
							motor[motorlift]=-40;
							wait1Msec(1250);
							motor[motorlift]=40;
							wait1Msec(750);
							}//close for loop*/
							stopAllTasks();
						}//close object drop loop

						motor[motorleft]=127-n;
						motor[motorright]=-127+n;
						if(SensorValue(IR1)>IRmax-(30-s)){
							IRmax=SensorValue(IR1);
							while(getMotorEncoder(motorIR)>-2){
								//	motor[motorIR]=0;
								motor[motorleft]=2;
								//	motor[motorright]=-30;
								if(SensorValue(IR1)<IRmax-5){
									motor[motorIR]=-40;
								}//closes if loop

							}//closes while loop
							if((50-V)>35){
								V=V+1;}
							if((30-s)>5){
								s=s+1;}
							if((300-v)>50){
								v=v+4;}
							if((127-n)>60){
								n=n+1;	}
						}//closes IRmax loop

					}//closes motorIR<156.8 loop


					while(getMotorEncoder(motorIR)>(-300+v)){
						motor[motorIR]=-60+V;
						if ((SensorValue(sonar)<3.25 && SensorValue(sonar)>0) && (SensorValue(IR1)> 500)){
							motor[motorleft]=0;
							motor[motorright]=0;
							motor[motorIR]=0;
							wait1Msec(250);
							motor[motorlift]=-50;
							wait1Msec(750);
							motor[motorlift]=0;
							wait1Msec(100);
							motor[EMAGNET]=0;
							wait1Msec(1000);
							motor[motorlift]=40;
							wait1Msec(750);
							motor[motorlift]=0;
							motor[motorleft]=-50;
							motor[motorright]=50;
							wait1Msec(1500);
							motor[motorleft]=0;
							motor[motorright]=0;
							wait1Msec(1000);
							/*
							for(int y=0; y<3; y++){
							motor[motorlift]=-40;
							wait1Msec(1250);
							motor[motorlift]=40;
							wait1Msec(750);
							}//close for loop*/
							stopAllTasks();
						}//close object drop loop

						motor[motorleft]=127-n;
						motor[motorright]=-127+n;
						if(SensorValue(IR1)>IRmax-(30-s)){
							IRmax=SensorValue(IR1);
							while(getMotorEncoder(motorIR)<2){
								//		motor[motorIR]=0;
								//	motor[motorleft]=30;
								motor[motorright]=-2;
								if(SensorValue(IR1)<IRmax-5){
									motor[motorIR]=40;
								}//closes if loop

							}//closes while looV
							if((50-V)>35){
								V=V+1;}
							if((30-s)>5){
								s=s+1;}
							if((300-v)>50){
								v=v+4;}
							if((127-n)>60){
								n=n+1;
							}
						}//closes IRmax loop

					}//closes motorIR<156.8 loop





				}//closes drive while loop


			}//closes button1 while loop

		}//closes button1 if loop

	}//closes x==1 while

}//closes main

task main()
{
	motor[EMAGNET]=0;
	resetMotorEncoder(motorIR);

	run();
}
